<?php

namespace App\Enums;

enum TagEstabelecimento: string
{
    case SUPERMERCADO = 'SUPERMERCADO';
    case PADARIA = 'PADARIA';
    case FARMACIA = 'FARMACIA';
    case ACADEMIA = 'ACADEMIA';
    case PETSHOP = 'PETSHOP';
    case CLINICA_MEDICA = 'CLINICA_MEDICA';
    case CLINICA_ODONTOLOGICA = 'CLINICA_ODONTOLOGICA';
    case ESCOLA = 'ESCOLA';
    case CRECHE = 'CRECHE';
    case LOJA_ROUPAS = 'LOJA_ROUPAS';
    case LOJA_CALCADOS = 'LOJA_CALCADOS';
    case LOJA_ELETRONICOS = 'LOJA_ELETRONICOS';
    case LOJA_MOVEIS = 'LOJA_MOVEIS';
    case RESTAURANTE = 'RESTAURANTE';
    case LANCHONETE = 'LANCHONETE';
    case BAR = 'BAR';
    case PIZZARIA = 'PIZZARIA';
    case SORVETERIA = 'SORVETERIA';
    case SALAO_BELEZA = 'SALAO_BELEZA';
    case BARBEARIA = 'BARBEARIA';
    case LAVA_RAPIDO = 'LAVA_RAPIDO';
    case MECANICA = 'MECANICA';
    case BORRACHARIA = 'BORRACHARIA';
    case POSTO_COMBUSTIVEL = 'POSTO_COMBUSTIVEL';
    case PAPELARIA = 'PAPELARIA';
    case COPIADORA = 'COPIADORA';
    case LOJA_MATERIAIS_CONSTRUCAO = 'LOJA_MATERIAIS_CONSTRUCAO';
    case LOJA_DEPARTAMENTO = 'LOJA_DEPARTAMENTO';
    case SHOPPING = 'SHOPPING';
    case FLORICULTURA = 'FLORICULTURA';
    case LOJA_ARTESANATO = 'LOJA_ARTESANATO';
    case LOJA_BRINQUEDOS = 'LOJA_BRINQUEDOS';
    case LOJA_ACESSORIOS = 'LOJA_ACESSORIOS';
    case CONFEITARIA = 'CONFEITARIA';
    case LOJA_COSMETICOS = 'LOJA_COSMETICOS';
    case CLINICA_ESTETICA = 'CLINICA_ESTETICA';
    case OFICINA_MOTOS = 'OFICINA_MOTOS';
    case PAPELARIA_ESCOLAR = 'PAPELARIA_ESCOLAR';
    case MERCEARIA = 'MERCEARIA';
    case LOJA_UTILIDADES = 'LOJA_UTILIDADES';
    case LOJA_INFORMATICA = 'LOJA_INFORMATICA';
    case LOJA_CELULARES = 'LOJA_CELULARES';
    case LOJA_OCULOS = 'LOJA_OCULOS';
    case LAVANDERIA = 'LAVANDERIA';
    case LOJA_PRESENTES = 'LOJA_PRESENTES';
    case AGENCIA_VIAGENS = 'AGENCIA_VIAGENS';
    case LOJA_INSTRUMENTOS = 'LOJA_INSTRUMENTOS';
    case LOJA_ARTIGOS_ESPORTIVOS = 'LOJA_ARTIGOS_ESPORTIVOS';
    case LOJA_ARTIGOS_PESCA = 'LOJA_ARTIGOS_PESCA';
    case COWORKING = 'COWORKING';
    case CLINICA_FISIOTERAPIA = 'CLINICA_FISIOTERAPIA';
    case CLINICA_VETERINARIA = 'CLINICA_VETERINARIA';
    case LOJA_JOIAS = 'LOJA_JOIAS';
    case LOJA_VEICULOS = 'LOJA_VEICULOS';
    case ACADEMIA_PILATES = 'ACADEMIA_PILATES';
    case ACADEMIA_DANCA = 'ACADEMIA_DANCA';
    case SPA = 'SPA';
    case CLINICA_NUTRICAO = 'CLINICA_NUTRICAO';
    case CENTRO_REABILITACAO = 'CENTRO_REABILITACAO';
    case COOPERATIVA_ALIMENTAR = 'COOPERATIVA_ALIMENTAR';
    case MERCADINHO = 'MERCADINHO';
    case LOJA_HORTIFRUTI = 'LOJA_HORTIFRUTI';
    case LOJA_SOLAR = 'LOJA_SOLAR';
    case BICICLETERIA = 'BICICLETERIA';
    case ESCOLA_ARTES = 'ESCOLA_ARTES';
    case ESCOLA_MUSICAL = 'ESCOLA_MUSICAL';
    case ESTUDIO_FOTOGRAFIA = 'ESTUDIO_FOTOGRAFIA';
    case TEATRO = 'TEATRO';
    case CINEMA = 'CINEMA';
    case HOTEL = 'HOTEL';
    case POUSADA = 'POUSADA';
    case HOSTEL = 'HOSTEL';
    case RESTAURANTE_VEGETARIANO = 'RESTAURANTE_VEGETARIANO';
    case RESTAURANTE_TERREO = 'RESTAURANTE_TERREO';
    case DRINK_BAR = 'DRINK_BAR';
    case CASA_CARNES = 'CASA_CARNES';
    case LOJA_SAQUES_PET = 'LOJA_SAQUES_PET';
    case LOJA_CERVEJA_ARTESANAL = 'LOJA_CERVEJA_ARTESANAL';
    case CLINICA_PODOLOGICA = 'CLINICA_PODOLOGICA';
    case LOJA_DEPARTAMENTO_BEBES = 'LOJA_DEPARTAMENTO_BEBES';
    case LOJA_RELOGIOS = 'LOJA_RELOGIOS';
    case LOJA_TECIDOS = 'LOJA_TECIDOS';
    case LOJA_FERRAMENTAS = 'LOJA_FERRAMENTAS';
    case OFICINA_DE_BICICLETA = 'OFICINA_DE_BICICLETA';
    case ESTUDIO_YOGA = 'ESTUDIO_YOGA';
    case ESTUDIO_ARTISTICO = 'ESTUDIO_ARTISTICO';
    case ESCOLA_CIVIL = 'ESCOLA_CIVIL';
    case ACADEMIA_LUTAS = 'ACADEMIA_LUTAS';
    case LOJA_CONFECCOES = 'LOJA_CONFECCOES';
    case LOJA_PLANTAS = 'LOJA_PLANTAS';
    case LOJA_DOCES = 'LOJA_DOCES';
    case BAZAR = 'BAZAR';
    case LOJA_SURF = 'LOJA_SURF';
    case CLINICA_EEG = 'CLINICA_EEG';
    case CENTRO_IDOSO = 'CENTRO_IDOSO';
    case ESCOLA_INFANTIL = 'ESCOLA_INFANTIL';
    case CASA_NOTURNA = 'CASA_NOTURNA';

    public function label(): string
    {
        return match ($this) {
            self::SUPERMERCADO => 'Supermercado',
            self::PADARIA => 'Padaria',
            self::FARMACIA => 'Farmácia',
            self::ACADEMIA => 'Academia',
            self::PETSHOP => 'Pet Shop',
            self::CLINICA_MEDICA => 'Clínica Médica',
            self::CLINICA_ODONTOLOGICA => 'Clínica Odontológica',
            self::ESCOLA => 'Escola',
            self::CRECHE => 'Creche',
            self::LOJA_ROUPAS => 'Loja de Roupas',
            self::LOJA_CALCADOS => 'Loja de Calçados',
            self::LOJA_ELETRONICOS => 'Loja de Eletrônicos',
            self::LOJA_MOVEIS => 'Loja de Móveis',
            self::RESTAURANTE => 'Restaurante',
            self::LANCHONETE => 'Lanchonete',
            self::BAR => 'Bar',
            self::PIZZARIA => 'Pizzaria',
            self::SORVETERIA => 'Sorveteria',
            self::SALAO_BELEZA => 'Salão de Beleza',
            self::BARBEARIA => 'Barbearia',
            self::LAVA_RAPIDO => 'Lava Rápido',
            self::MECANICA => 'Oficina Mecânica',
            self::BORRACHARIA => 'Borracharia',
            self::POSTO_COMBUSTIVEL => 'Posto de Combustível',
            self::PAPELARIA => 'Papelaria',
            self::COPIADORA => 'Copiadora',
            self::LOJA_MATERIAIS_CONSTRUCAO => 'Materiais de Construção',
            self::LOJA_DEPARTAMENTO => 'Loja de Departamento',
            self::SHOPPING => 'Shopping Center',
            self::FLORICULTURA => 'Floricultura',
            self::LOJA_ARTESANATO => 'Loja de Artesanato',
            self::LOJA_BRINQUEDOS => 'Loja de Brinquedos',
            self::LOJA_ACESSORIOS => 'Loja de Acessórios',
            self::CONFEITARIA => 'Confeitaria',
            self::LOJA_COSMETICOS => 'Loja de Cosméticos',
            self::CLINICA_ESTETICA => 'Clínica de Estética',
            self::OFICINA_MOTOS => 'Oficina de Motos',
            self::PAPELARIA_ESCOLAR => 'Papelaria Escolar',
            self::MERCEARIA => 'Mercearia',
            self::LOJA_UTILIDADES => 'Loja de Utilidades',
            self::LOJA_INFORMATICA => 'Loja de Informática',
            self::LOJA_CELULARES => 'Loja de Celulares',
            self::LOJA_OCULOS => 'Loja de Óculos',
            self::LAVANDERIA => 'Lavanderia',
            self::LOJA_PRESENTES => 'Loja de Presentes',
            self::AGENCIA_VIAGENS => 'Agência de Viagens',
            self::LOJA_INSTRUMENTOS => 'Loja de Instrumentos Musicais',
            self::LOJA_ARTIGOS_ESPORTIVOS => 'Artigos Esportivos',
            self::LOJA_ARTIGOS_PESCA => 'Artigos para Pesca',
            self::COWORKING => 'Espaço Coworking',
            self::CLINICA_FISIOTERAPIA => 'Clínica de Fisioterapia',
            self::CLINICA_VETERINARIA => 'Clínica Veterinária',
            self::LOJA_JOIAS => 'Joalheria',
            self::LOJA_VEICULOS => 'Loja de Veículos',
            self::ACADEMIA_PILATES => 'Academia (Pilates)',
            self::ACADEMIA_DANCA => 'Academia de Dança',
            self::SPA => 'Spa',
            self::CLINICA_NUTRICAO => 'Clínica de Nutrição',
            self::CENTRO_REABILITACAO => 'Centro de Reabilitação',
            self::COOPERATIVA_ALIMENTAR => 'Cooperativa Alimentar',
            self::MERCADINHO => 'Mercadinho',
            self::LOJA_HORTIFRUTI => 'Hortifruti',
            self::LOJA_SOLAR => 'Loja de Painéis Solares',
            self::BICICLETERIA => 'Bicicleteria',
            self::ESCOLA_ARTES => 'Escola de Artes',
            self::ESCOLA_MUSICAL => 'Escola de Música',
            self::ESTUDIO_FOTOGRAFIA => 'Estúdio de Fotografia',
            self::TEATRO => 'Teatro',
            self::CINEMA => 'Cinema',
            self::HOTEL => 'Hotel',
            self::POUSADA => 'Pousada',
            self::HOSTEL => 'Hostel',
            self::RESTAURANTE_VEGETARIANO => 'Restaurante Vegetariano',
            self::RESTAURANTE_TERREO => 'Restaurante Gourmet',
            self::DRINK_BAR => 'Drink Bar',
            self::CASA_CARNES => 'Casa de Carnes',
            self::LOJA_CERVEJA_ARTESANAL => 'Cervejaria Artesanal',
            self::CLINICA_PODOLOGICA => 'Clínica Podológica',
            self::LOJA_RELOGIOS => 'Loja de Relógios',
            self::LOJA_TECIDOS => 'Loja de Tecidos',
            self::LOJA_FERRAMENTAS => 'Loja de Ferramentas',
            self::OFICINA_DE_BICICLETA => 'Oficina de Bicicletas',
            self::ESTUDIO_YOGA => 'Estúdio de Yoga',
            self::ESTUDIO_ARTISTICO => 'Estúdio Artístico',
            self::ACADEMIA_LUTAS => 'Academia de Lutas',
            self::LOJA_CONFECCOES => 'Loja de Confecções',
            self::LOJA_PLANTAS => 'Loja de Plantas',
            self::LOJA_DOCES => 'Doceria',
            self::BAZAR => 'Bazar',
            self::LOJA_SURF => 'Loja de Surf',
            self::CENTRO_IDOSO => 'Centro do Idoso',
            self::ESCOLA_INFANTIL => 'Escola Infantil',
            self::CASA_NOTURNA => 'Casa Noturna',
            self::LOJA_SAQUES_PET => 'Loja de Saques Pet',
            self::LOJA_DEPARTAMENTO_BEBES => 'Loja de Departamento de Bebes',
            self::ESCOLA_CIVIL => 'Escola Civil',
            self::CLINICA_EEG => 'Clínica EEG',
        };
    }

    public static function toSelect(): array
    {
        return array_map(fn($tag) => [
            'value' => $tag->value,
            'label' => $tag->label(),
        ], self::cases());
    }
}
